import streamlit as st
import pandas as pd
from sqlalchemy import text
import plotly.express as px
import plotly.graph_objects as go
from queries import delay_analysis

from db_config import engine

st.title("⏱️ Demo Follow-Up Delay vs Conversion Analysis")


df = pd.read_sql(delay_analysis, engine)

st.dataframe(df, use_container_width=True)

# ==============================
# KPI Metrics
# ==============================
st.divider()
col1, col2, col3 = st.columns(3)

best_rate = df["conversion_rate"].max()
best_delay = df.loc[
    df["conversion_rate"].idxmax(),
    "delay_days"
]

avg_rate = round(df["conversion_rate"].mean(), 2)

col1.metric(
    "🏆 Best Conversion Rate",
    f"{best_rate}%"
)

col2.metric(
    "⚡ Best Follow-Up Delay",
    f"{best_delay} Day(s)"
)

col3.metric(
    "📈 Average Conversion Rate",
    f"{avg_rate}%"
)

st.divider()

# ==============================
# Chart 1
# ==============================

fig1 = px.bar(
    df,
    x="delay_days",
    y="conversion_rate",
    text="conversion_rate",
    title="Conversion Rate by Follow-Up Delay",
)

fig1.update_traces(
    texttemplate='%{text:.2f}%',
    textposition='outside'
)

fig1.update_layout(
    xaxis_title="Delay After Demo (Days)",
    yaxis_title="Conversion Rate (%)",
    height=500
)

st.plotly_chart(fig1, use_container_width=True)

# ==============================
# Chart 2
# ==============================

fig2 = go.Figure()

fig2.add_trace(
    go.Scatter(
        x=df["delay_days"],
        y=df["total_leads"],
        mode="lines+markers",
        name="Total Leads"
    )
)

fig2.add_trace(
    go.Scatter(
        x=df["delay_days"],
        y=df["converted_leads"],
        mode="lines+markers",
        name="Converted Leads"
    )
)

fig2.update_layout(
    title="Lead Volume vs Successful Conversions",
    xaxis_title="Follow-Up Delay (Days)",
    yaxis_title="Number of Leads",
    height=500
)

st.plotly_chart(fig2, use_container_width=True)


# ==============================
# Insights
# ==============================

st.markdown("## 💡 Business Insights")

st.success("""
### Key Findings

• Students who received a follow-up call on the same day as watching the demo achieved the highest conversion rate of **41.30%**.

• Conversion rate dropped to **29.85%** when the first follow-up was delayed by just **1 day**.

• Students contacted after **2 days** showed the lowest conversion rate at only **14.29%**.

• Delays beyond the demo day consistently resulted in weaker conversion performance.
""")

st.info("""
### Student Behavior Insights

• Interest levels are highest immediately after students watch the demo.

• As the delay increases, students may lose interest, forget details, become busy, or evaluate competitors.

• Same-day engagement helps capitalize on the momentum generated by the demo session.
""")

st.warning("""
### Revenue Leakage

• 102 students were contacted after at least one day of delay.

• These delayed groups collectively achieved lower conversion rates than the same-day group.

• A portion of lost conversions may be attributable to delayed counselor outreach rather than student intent.
""")

st.markdown("""
###  Recommended Actions

- Make same-day post-demo follow-up mandatory.

- Create automated reminders for counselors immediately after demo completion.

- Track average follow-up delay as a sales KPI.

- Escalate leads that remain untouched for more than 24 hours.

- Replicate the process used for same-day follow-ups across all sales teams.
""")

st.success("""
### 💰 Business Impact

This analysis demonstrates that follow-up speed directly affects conversion outcomes.

Students contacted on the same day converted at nearly **3x the rate** of those contacted after 2 days.

Improving counselor responsiveness can increase enrollments without increasing marketing spend, making it one of the highest ROI process improvements available.
""")